FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^eis/', include('applications.eis.urls', namespace='eis')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls', namespace='placement')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    url(r'^aims/', include('applications.academic_information.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

FusionIIIT/applications/feeds/urls.py
from django.conf.urls import url

from . import views

app_name = 'feeds'

urlpatterns=[
	url(r'^$', views.feeds, name= 'feeds'),
	url(r'^request/$', views.Request, name= 'request'),
	url(r'^comment_text/$', views.Comment_Text, name='comment_text'),
	url(r'^reply_text/$', views.Reply_Text, name='reply_text'),
	url(r'^like_comment/$', views.LikeComment, name='like_comment'),
	url(r'^(?P<id>[0-9]+)/delete_post/$', views.delete_post, name='delete_post'),
	url(r'^(?P<id>[0-9]+)/update_post/$', views.update_post, name='update_post'),
	url(r'^(?P<string>[-\w]+)/$', views.TagsBasedView, name= 'tag_based_view'),
	url(r'^remove_tag/$', views.RemoveTag, name= 'remove_tag'),
	url(r'^question_id_/(?P<id>[0-9]+)/$', views.ParticularQuestion, name= 'single_question'),
]

FusionIIIT/applications/feeds/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from markdown_deux import markdown

from applications.globals.models import ExtraInfo


class Constants:

	TAG_LIST = (
		('CSE', 'CSE'),
		('ECE', 'ECE'),
		('Mechanical', 'Mechanical'),
		('Technical-Clubs', 'Technical Clubs'),
		('Cultural-Clubs', 'Cultural Clubs'),
		('Sports-Clubs', 'Sports Clubs'),
		('Business-and-Career', 'Business and Career'),
		('Entertainment', 'Entertainment'),
		('IIITDMJ-Campus', 'IIITDMJ Campus'),
		('Jabalpur-city', 'Jabalpur city'),
		('IIITDMJ-Rules-and-Regulations', 'IIITDMJ rules and regulations'),
		('Academics', 'Academics'),
		('IIITDMJ', 'IIITDMJ'),
		('Life-Relationship-and-Self', 'Life Relationship and Self'),
		('Technology-and-Education', 'Technology and Education'),       
		('Programmes', 'Programmes'),
		('Others', 'Others'),
	)

	SUBTAG_LIST = (
		('Web-Development', 'Web Development'),
		('Competitive-Programming', 'Competitive Programming'),
		('Programming-Languages', 'Programming-Languages'),
		('Data-Science', 'Data-Science'),
		('Ethical-Hacking-and-Cyber-Security', 'Ethical hacking and cyber security'),
		('Cryptography-and-Network-Security', 'cryptography and network security'),
		('Software-Engineering', 'Software-Engineering'),
		('Algorithm', 'Algorithm'),
		('Mobile-Development', 'Mobile-Development'),
		('Game-Development', 'Game-Development'),
		('Artificial-Intelligence', 'Artificial Intelligence'),

		('Electronics-Circuit-Design', 'Electronics Circuit Design'),
		('Wireless-Communication', 'Wireless Communication'),
		('Embedded-System', 'Embedded Systems'),
		('VLSI', 'VLSI'),
		('Control-System', 'Control Systems'),
		('Robotics-and-others', 'Robotics and Others'),
		('Microcontrollers', 'Microcontrollers'),
		('IOT', 'IOT'),

		('Robotics', 'Robotics'),
		('Thermodynamics', 'Thermodynamics'),
		('Nanatechnology', 'Nanatechnology'),
		('Manufacturing', 'Manufacturing'),

		('Programming-and-Webix-Club', 'Programming and Webix Club'),
		('Electronics-Club', 'Electronics Club'),
		('Business-and-Management-Club', 'Business and Management Club'),
		('Robotics-Club', 'Robotics Club'),
		('CAD-Club', 'CAD Club'),
		('Astronomy-and-Physics-Society', 'ASTRONOMY AND PHYSICS SOCIETY'),
		('Aakriti-The-Film-Making-and-Photography-Club', 'AAKRITI-THE FILM MAKING AND PHOTOGRAPHY CLUB'),
		('AUTOMOTIVE-AND-FABRICATION-CLUB', 'AUTOMOTIVE AND FABRICATION CLUB'),
		('RACING-CLUB', 'RACING CLUB'),

		('SAAZ-MUSIC-CLUB', 'SAAZ-MUSIC CLUB'),
		('SAMVAAD-THE-LITERATURE-AND-QUIZZING-SOCIETY', 'SAMVAAD-THE LITERATURE AND QUIZZING SOCIETY'),
		('ABHIVYAKTI-ARTS-CLUB', 'ABHIVYAKTI-ARTS CLUB'),
		('JAZBAAT-THE-DRAMATICS-SOCIETY', 'JAZBAAT-THE DRAMATICS SOCIETY'),
		('AAVARTAN-DANCE-CLUB', 'AAVARTAN-DANCE CLUB'),

		('BADMINTON-CLUB', 'BADMINTON CLUB'),
		('LAWN-TENNIS-&-BASKETBALL-CLUB', 'LAWN TENNIS&BASKETBALL CLUB'),
		('TABLE-TENNIS', 'TABLE TENNIS'),
		('CHESS-&-CARROM-CLUB', 'CHESS & CARROM CLUB'),
		('CRICKET-CLUB', 'CRICKET CLUB'),
		('FOOTBALL-CLUB', 'FOOTBALL CLUB'),
		('VOLLEYBALL-CLUB', 'VOLLEYBALL CLUB'),
		('ATHLETICS-CLUB', 'ATHLETICS CLUB'),

		('Business-Models-and-Strategies', 'Business Models and strategies'),
		('Startups-and-Stratup-Strategies', 'Startups and Stratup Strategies'),
		('Entrepreneurship', 'Entrepreneurship'),
		('Finance', 'Finance'),
		('Marketing', 'Marketing'),
		('Stock-Market', 'Stock market'),
		('Career-Advice', 'Career Advice'),
		('Job-Interviews', 'Job Interviews'),

		('Journalism', 'Journalism'),
		('Entertainment', 'Entertainment'),
		('Hollywood-and-Movies', 'Hollywood and Movies'),
		('Music', 'Music'),
		('Fashion-and-Style', 'Fashion and Style'),

		('IIITDMJ-Campus', 'IIITDMJ-Campus'),

		('Jabalpur-City', 'Jabalpur City'),

		('IIITDMJ-rules-and-Regulations', 'IIITDMJ rules and regulations'),

		('Academic-Office-Stuffs', 'Academic office stuffs'),
		('Academic-Courses', 'Academic courses'),

		('Central-Mess', 'Central Mess'),
		('Alumni', 'Alumni'),
		('Hostels', 'Hostels'),
		('PHC', 'PHC'),
		('Activities', 'Activities'),
		('Counselling', 'Counselling'),
		('Achievments', 'Achievments'),
		('Library', 'Library'),
		('Faculty', 'Faculty'),
		('Staff', 'Staff'),
		('College-Fest', 'College Fest'),
		('Workshops', 'Workshops'),
		('Campus-Recruitments', 'Campus Recruitments'),
		('Jagrati', 'Jagrati'),

		('Self-Improvement', 'Self Improvement'),
		('Friendship', 'Friendship'),
		('Experiences', 'Experiences'),
		('Dating-and-Relationships', 'Dating and Relationships'),
		('Interpersonal-Interactions', 'Interpersonal Interactions'),
		('Life-and-Social-Advice', 'Life and Social Advice'),
		('Philosophy', 'Philosophy'),

		('Technology-Trends', 'Technology Trends'),
		('TED', 'TED'),
		('Higher-Education', 'Higher Education'),
		('Science-and-Universe', 'Science and Universe'),
		('Social-Media', 'Social-Media'),
		('Toron', 'Toron'),
		('Jobs-and-Internships', 'Jobs and Internships'),

		('Btech', 'Btech'),
		('Mtech', 'Mtech'),
		('Bdes', 'Bdes'),
		('Mdes', 'Mdes'),
		('Phd', 'Phd'),
		('Mechatronics', 'Mechatronics'),

		('others', 'others'),

	)


# Create your models here.


class AllTags(models.Model):
    # new = models.CharField(max_length=100, blank=True, null=True)
	tag = models.CharField(max_length=100, default='CSE', choices=Constants.TAG_LIST)
	subtag = models.CharField(max_length=100, unique=True, default='Web-Development', choices=Constants.SUBTAG_LIST)

	def __str__(self):
		return '{} - {}'.format(self.tag, self.subtag)

class AskaQuestion(models.Model):
	can_delete=models.BooleanField(default=False)
	can_update=models.BooleanField(default=False)
	user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
	subject = models.CharField(max_length=100, blank=False)
	description = models.CharField(max_length=500, null=True, blank=True, default="")
	select_tag = models.ManyToManyField(AllTags)
	file = models.FileField(null=True, blank=True)
	uploaded_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)
	#like = models.IntegerField(default=0)
	likes = models.ManyToManyField(User, default=1,related_name='likes', blank=True)
	requests = models.ManyToManyField(User, default=1,related_name='requests', blank=True)
	#dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)
	is_liked=models.BooleanField(default=False)
	is_requested=models.BooleanField(default=False)
	request = models.IntegerField(default=0)
	anonymous_ask = models.BooleanField(default=False)
	total_likes=models.IntegerField(default=0)
	total_dislikes=models.IntegerField(default=0)

	# class Meta:
	# 	unique_together = ('subject', 'select_tag')

	def total_likes(self):
		return self.likes.count()

	def total_requests(self):
		return self.requests.count()

	def get_markdown(self):
		content = self.description
		markdown_text = markdown(content)
		markdown_text = mark_safe(markdown_text)
		return markdown_text
			
	def __str__(self):
		return '{} added ----> {} in {}'.format(self.user, self.subject, self.select_tag)

class AnsweraQuestion(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	content = models.TextField(max_length=1000, blank=False)
	question = models.ForeignKey(AskaQuestion, default=1, on_delete=models.CASCADE)
	uploaded_at = models.DateTimeField(auto_now=False, auto_now_add=False, default=timezone.now)
	answers = models.ManyToManyField(User, default=1, related_name='answers', blank=True)
	total_answers = models.IntegerField(default=0)

	def __str__(self):
		return '{} - answered the question - {}'.format(self.content, self.question)

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		markdown_text = mark_safe(markdown_text)
		return markdown_text

	def total_answers(self):
		return self.answers.count()


class Comments(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	question = models.ForeignKey(AskaQuestion, default=1 , on_delete = models.CASCADE)
	comment_text = models.CharField(max_length=5000)
	likes_comment = models.ManyToManyField(User, default=1,related_name='likes_comment', blank=True)
	total_likes_comment = models.IntegerField(default=0)
	commented_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)
	is_liked = models.BooleanField(default=False)

	def __str__(self):
		return self.comment_text

	def total_likes_comment(self):
		return self.likes_comment.count()

class Reply(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comments,default=1, on_delete=models.CASCADE)
	msg = models.CharField(max_length=1000)
	content = models.CharField(max_length=5000, default="")
	replies = models.ManyToManyField(User, default=1,related_name='replies', blank=True)
	total_replies = models.IntegerField(default=0)
	replied_at = models.DateTimeField(auto_now_add=False, auto_now=False, default=timezone.now)

	def __str__(self):
		return '{} - replied on  - {} at {}'.format(self.user, self.comment, self.replied_at)

	def total_replies(self):
		return self.replies.count()


class report(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	question = models.ForeignKey(AskaQuestion, default=1, on_delete = models.CASCADE)
	report_msg = models.CharField(max_length=1000,default="")

	# class Meta:
	# 	unique_together = ('user', 'question')



class hidden(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	question = models.ForeignKey(AskaQuestion, default=1, on_delete=models.CASCADE)
	# hide = models.BooleanField(default=False)

	class Meta:
		unique_together = ('user', 'question')

	def __str__(self):
		return '{} - hide - {}'.format(self.user, self.question)


class tags(models.Model):
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

FusionIIIT/applications/feeds/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

from .models import AnsweraQuestion, AskaQuestion, Comments


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields = ('comment_text',)

class AnswerForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	class Meta:
		model = AnsweraQuestion
		fields = [
			'content'
		]

class QuestionForm(forms.ModelForm):
	description = forms.CharField(widget=PagedownWidget(show_preview=False))
	class Meta:
		model = AskaQuestion
		fields = [
			'description',
		]

FusionIIIT/templates/feeds/answer_display.html
{{ instance.get_markdown }}

FusionIIIT/templates/feeds/comment_text.html
{% load static %}

<!-- Comments Header -->
<div>
	<div style="font-size: 20px; color: #6698FF;" class="header">
		Comments
		<i class="ui right labeled icon caret right"></i>
		<br>		
	</div>

	<!-- Scrollable Comments Section -->
	<div class="hidden">
		<div id="style-1" class="ui message scrollbar">
			<!-- <div class="ui segment force-overflow"> -->
			{% for comment in question.comments_set.all|dictsortreversed:"commented_at" %}						
				<br>
				<div style="display: inline;">
					<a href=""><img class="ui avatar image" src="{% static 'globals/img/zlatan.jpg' %}"></a>
				</div>
				<span style="font-size: 15px; padding-left: 5px;">{{ comment.comment_text }}</span>
				<footer style="color: rgba(0,0,0,.6); padding-left: 50px;">
					<small>-{{comment.user}} | {{comment.commented_at|timesince}} ago</small>
				</footer>

				<!-- Comment_Like Button Section starts here -->
				<div style="display: inline;" id="like-section-comment{{comment.id}}">
					{% include 'feeds/like_section_comment.html' %}		
				</div>
				<!-- Comment Like Button section ends here -->

				<button class="ui button" style="background-color: transparent;" onclick="reply_btn('{{comment.id}}');">
					<span style="color: #6495ed;font-size: 12px;">Replies({{comment.reply_set.count}})</span>
				</button>

				
				<div id="reply{{comment.id}}" style="display: none;">
					<div class="ui grid">
						<div class="ui two wide column"></div>

						<div class="ui fourteen wide column">
							<blockquote style="margin-left: 15px;">		
								<form id="{{comment.id}}" class="reply-form" method="POST" action=".">{% csrf_token %}
									<div style="display: none;" id="unique_{{comment.id}}">{{question.id}}</div>
									<div class="ui form">
										<div class="field">
											<textarea id="reply_text{{comment.id}}" name="reply_text" rows=2 cols="10"></textarea>
										</div>
										<input type="hidden" name="ques" value="{{question.id}}">
										<input class="ui mini blue basic button" type="submit" name="reply_button" value="Submit">
									</div>
								</form>
								<br>
								<p style="font-style: italic; font-weight: bold;">
									{{comment.reply_set.count}} replies
								</p>
								<hr>
								<br>
								<div style="left: 40px; border-left: 100px solid #d9deea;border-left-width: 1px; border-left-style: solid; border-left-color: rgb(217, 222, 234);">
								{% for reply in comment.reply_set.all|dictsortreversed:"replied_at" %}
									{{reply.content}}
									<footer>
										<small style="color: rgba(0,0,0,.6);">-{{reply.user}} | {{reply.replied_at|timesince}} ago</small>
									</footer>
									<!-- <p style="color: rgba(0,0,0,.6); padding-left: 3px;"></p> -->
									<div class="ui divider"></div>
								{% endfor %}
								</div>
							</blockquote>
						</div>
					</div>
				</div>

				<div class="ui divider"></div>	
				
			{% empty %}
				<p>No comments here yet :(</p>
			{% endfor %}
		<!-- </div> -->
	</div>
	</div>
</div>

FusionIIIT/templates/feeds/like_section_comment.html
<form style="display: inline;" method="post" action="{% url 'feeds:like_comment' %}" >
	{% csrf_token %}

	{% if comment.is_liked %}		
		<div style="padding-left: 50px; display: inline;" type="submit" id="like_comment_id" value="{{comment.id}}">
			<a href="" style="text-decoration: none;"><i class="thumbs up icon">({{ comment.total_likes_comment }})</i></a>
		</div>
		
	{% else %}	
		<div style="padding-left: 50px; display: inline;" type="submit" id="like_comment_id" value="{{comment.id}}">
			<a href="" style="text-decoration: none;"><i class="thumbs up outline icon">({{ comment.total_likes_comment }})</i></a>
		</div>

	{% endif %}
</form>

FusionIIIT/templates/feeds/question_request_count.html
<form style="display: inline;" method="POST" action="{% url 'feeds:request' %}">	
	<div style="font-weight: bold; box-sizing: inherit">
		{{ question.total_requests }} people requested
	</div>
	<br>

	{% if question.is_requested is True %}
		<button type="submit" value="{{question.id}}" class="ui positive button" id="request">
			Requested
		</button>
	{% else %}
		<button type="submit" value="{{question.id}}" class="ui button" id="request">
			Request
		</button>
	{% endif %}
</form>

FusionIIIT/templates/feeds/reply_section.html
{% for reply in comment.reply_set.all|dictsortreversed:"replied_at" %}
	{{reply.content}}
	<p>-{{reply.user}}</p>
	<p>{{reply.replied_at}}</p>
	<br>
{% endfor %}

FusionIIIT/templates/feeds/testing.html
<!DOCTYPE html>
<html>
	<head>
		<title>Hello It's Alpha</title>
	</head>
	<body>
		<h1>Hello there kjsndks ksdjn</h1>
	</body>
</html>