FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^eis/', include('applications.eis.urls', namespace='eis')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls', namespace='placement')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    url(r'^aims/', include('applications.academic_information.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

FusionIIIT/applications/office_module/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'office'

urlpatterns = [

    url(r'^officeOfDeanPnD/submit$',views.submitRequest,name='pWorkRequest'),
    url(r'^officeOfDeanPnD/action$',views.action,name='action'),
    url(r'^officeOfPurchaseOfficer/',views.officeOfPurchaseOfficer, name ='officeOfPurchaseOfficer'),
    url(r'^apply_purchase/', views.apply_purchase, name='apply_purchase'),
    url(r'^after_purchase/', views.after_purchase, name='after_purchase'),
    url(r'^officeOfRegistrar/$', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^officeOfDeanRSPC/$', views.officeOfDeanRSPC, name='officeOfDeanRSPC'),

    url(r'^officeOfDeanRSPC/submit/$',views.project_register,name='p_register'),
    url(r'^officeOfDeanRSPC/extention/$',views.project_extension,name='p_extension'),
    url(r'^officeOfDeanRSPC/close/$',views.project_closure,name='p_closure'),
    url(r'^officeOfDeanRSPC/reallocate/$',views.project_reallocation,name='p_reallocation'),
    url(r'^officeOfDeanRSPC/action/$',views.project_registration_permission,name='registration'),
    url(r'^officeOfDeanRSPC/extension/$',views.project_extension_permission,name='extension'),
    url(r'^officeOfDeanRSPC/closure/$',views.project_closure_permission,name='closure'),
    url(r'^officeOfDeanRSPC/reallocation/$',views.project_reallocation_permission,name='reallocation'),
    url(r'^officeOfDeanRSPC/forwarded/$',views.hod_action,name='hod_action'),
    url(r'^officeOfDeanRSPC/forwarded1/$',views.hod_closure,name='hod_closure'),
    url(r'^officeOfDeanRSPC/forwarded2/$',views.hod_extension,name='hod_extension'),
    url(r'^officeOfDeanRSPC/forwarded3/$',views.hod_allocation,name='hod_allocation'),
    url(r'^officeOfDeanRSPC/(?P<pr_id>[0-9]+)/$',views.pdf,name='pdf'),

    url(r'^eisModulenew/profile', views.eisModulenew, name='eisModulenew'),

    url(r'^officeOfDeanPnD/$', views.officeOfDeanPnD, name='officeOfDeanPnD'),
    url(r'^officeOfHOD/$', views.officeOfHOD, name='officeOfHOD'),
    url(r'^officeOfHOD/submit/$',views.teaching_form,name='teaching_form'),
    url(r'^officeOfHOD/work/$',views.hod_work,name='hod_work'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^deleteitem/(?P<id>[0-9]+)',views.delete_item, name='delete_item'),
    url(r'^deletevendor/(?P<id>[0-9]+)',views.delete_vendor, name='delete_vendor'),
    url(r'^editvendor/(?P<id>[0-9]+)',views.edit_vendor, name='edit_vendor'),
    url(r'^editvendor/office/officeOfPurchaseOfficer/edit/',views.edit,name='edit'),
    url(r'^edititem/(?P<id>[0-9]+)',views.edit_item, name='edit_item'),
    url(r'^edititem/office/officeOfPurchaseOfficer/edit1/',views.edit1,name='edit'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^directorOffice/$', views.directorOffice, name='directorOffice'),
    url(r'^directorOffice/appoint', views.appoint, name='appoint'),
    url(r'^directorOffice/meeting', views.meeting, name='meeting'),
    url(r'^officeOfRegistrar/upload/$', views.upload, name='upload'),
    url(r'^officeOfRegistrar/generalAdminForm/reject/$', csrf_exempt(views.admin_reject), name='admin_reject'),
    url(r'^officeOfDeanStudents/$', views.officeOfDeanStudents, name='officeOfDeanStudents'),
    url(r'^officeOfPurchaseOfficer/', views.officeOfPurchaseOfficr, name='officeOfPurchaseOfficer'),
    url(r'^officeOfRegistrar/', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^officeOfDeanStudents/holding_meeting', views.holdingMeeting, name='holdingMeetings'),
    url(r'^officeOfDeanStudents/meeting_Minutes', views.meetingMinutes, name='meetingMinutes'),
    url(r'^officeOfDeanStudents/hostelRoomAllotment', views.hostelRoomAllotment),
    url(r'^officeOfDeanStudents/budget_approval', views.budgetApproval),
    url(r'^officeOfDeanStudents/budget_rejection', views.budgetRejection),
    url(r'^officeOfDeanStudents/club_approval', views.clubApproval),
    url(r'^officeOfDeanStudents/club_rejection', views.clubRejection),
    url(r'^officeOfDeanStudents/budgetAllot', views.budgetAllot),
    url(r'^officeOfDeanStudents/budgetAllotEdit', views.budgetAllotEdit),
    url(r'^officeOfDeanAcademics/$', views.officeOfDeanAcademics, name='officeOfDeanAcademics'),

    url(r'^officeOfDeanAcademics/assistantship', views.assistantship, name='assistantship'),
    url(r'^officeOfDeanAcademics/formsubmit', views.formsubmit, name='formsubmit'),
    url(r'^officeOfDeanAcademics/init_assistantship', views.init_assistantship, name='init_assistantship'),
    url(r'^officeOfDeanAcademics/scholarshipform', views.scholarshipform),
    url(r'^officeOfDeanAcademics/applications', views.applications, name='applications'),
    url(r'^officeOfDeanAcademics/courses', views.courses, name='courses'),
    url(r'^officeOfDeanAcademics/scholarship', views.scholarship, name='scholarship'),
    url(r'^officeOfDeanAcademics/semresults', views.semresults, name='semresults'),
    url(r'^officeOfDeanAcademics/thesis', views.thesis, name='thesis'),
]

FusionIIIT/applications/office_module/forms.py
from django import forms

from .models import *


class Requisitionform(forms.ModelForm):
	class Meta:
		model=Requisitions
		fields=['title','department','building','description']

FusionIIIT/applications/office_module/views.py
import datetime
from datetime import date, datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from applications.academic_procedures.models import Thesis
from applications.globals.models import (Designation, ExtraInfo,
                                         HoldsDesignation, User)
from applications.scholarships.models import Mcm

from .forms import *
from .models import *
from .models import (Project_Closure, Project_Extension, Project_Reallocation,
                     Project_Registration)
from .views_office_students import *


def officeOfDeanRSPC(request):
    project=Project_Registration.objects.all()
    project1=Project_Extension.objects.all()
    project2=Project_Closure.objects.all()
    project3=Project_Reallocation.objects.all()

    design = HoldsDesignation.objects.filter(working=request.user)
    print(design)
    desig=[]
    for i in design:
        desig.append(str(i.designation))

    context = {'project':project, 'project1':project1, 'project2':project2, 'project3':project3, 'desig':desig}

    return render(request, "officeModule/officeOfDeanRSPC/officeOfDeanRSPC.html", context)

@login_required
def officeOfDeanPnD(request):
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    requisitions=Requisitions.objects.filter(userid=extrainfo)
    holds=HoldsDesignation.objects.filter(user=user)
    civilreq=Requisitions.objects.filter(department='civil',assign_title=None)
    electricalreq = Requisitions.objects.filter(department='electrical')
    req=Requisitions.objects.all()
    deslist=['Civil_JE','Civil_AE','EE','DeanPnD','Electrical_JE','Electrical_AE']
    deslist1=['Civil_JE','Civil_AE']
    design=HoldsDesignation.objects.filter(working=user)
    desig=[]
    for i in design:
        desig.append(str(i.designation))
    print(desig)

    if 'createassign' in request.POST:
        id=request.POST.get('req_id')
        obj = Requisitions.objects.get(id=id)
        obj.assign_title = request.POST.get('title')
        obj.assign_description = request.POST.get('description')
        obj.estimate=request.FILES['estimate']
        print(obj.estimate)
        obj.assign_date=timezone.now()
        obj.save()

        for hold in holds:
            if str(hold.designation.name) in deslist1:
                if str(hold.designation.name) == "Civil_JE":
                    receive=HoldsDesignation.objects.get(designation__name="Civil_AE")
                    sent=HoldsDesignation.objects.get(designation__name="Civil_JE")
                    fdate = datetime.now().date()

                elif str(hold.designation.name)=="Electrical_JE":
                    receive=ExtraInfo.objects.get(designation__name="Electrical_AE")
                    fdate = datetime.now().date()
        moveobj=Filemovement(rid=obj,sentby=sent,receivedby=receive)
        moveobj.save()



    if 'asearch' in request.POST:
        check=request.POST.get('status')
        dept=request.POST.get('dept')
        if dept=="all":
            req=Requisitions.objects.all()
        elif dept=="civil":
            req=Requisitions.objects.filter(department='civil')
        elif dept=="electrical":
            req=Requisitions.objects.filter(department='electrical')
        if check=="1":
            req=req
        elif check=="2":
            req=req.filter(tag=0)
        elif check=="3":
            req=req.filter(tag=1)

    sentfiles=''
    for des in design:
        if str(des.designation) in deslist:
            sentfiles=Filemovement.objects.filter(Q(sentby=des)|Q(actionby_receiver='accept'))

    print(sentfiles)

    files=''
    for des in design:
        if str(des.designation) in deslist:
            files=Filemovement.objects.filter(receivedby=des,actionby_receiver='')
    allfiles=Filemovement.objects.all()

    context = {'civilreq':civilreq,'electricalreq':electricalreq,'files':files,'req':req,'sentfiles':sentfiles,'allfiles':allfiles,'requisitions':requisitions,'desig':desig}
    return render(request, "officeModule/officeOfDeanPnD/officeOfDeanPnD.html", context)


@login_required
def submitRequest(request):

    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    fdate = datetime.now().date()
    dept=request.POST.get('department')
    building = request.POST.get('building')
    title = request.POST.get('title')
    description = request.POST.get('description')

    request_obj = Requisitions(userid=extrainfo, req_date=fdate,
                               description=description, department=dept, title=title, building=building)
    request_obj.save()
    context={}
    return HttpResponseRedirect("/office/officeOfDeanPnD")


@login_required
def action(request):
    deslist=['Civil_JE','Civil_AE','EE','DeanPnD','Electrical_JE','Electrical_AE']
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    design=HoldsDesignation.objects.filter(working=user)
    fdate = datetime.datetime.now().date()
    id=request.POST.get('select')
    fileobj=Filemovement.objects.get(pk=id)
    remarks=request.POST.get('remarks')
    sentby=''
    for des in deslist:
        try:
            sentby=HoldsDesignation.objects.get(working=user,designation__name=des)
        except :
            sentby=None

        if sentby :
            print(sentby)
            i=Designation.objects.get(name=des)
            i=i.id
            break

    reqobj=fileobj.rid

    if 'forward' in request.POST:
        fileobj.actionby_receiver="forward"
        fileobj.save()
        receive=HoldsDesignation.objects.get(designation__id=i+1)
        moveobj=Filemovement(rid=reqobj,sentby=sentby,receivedby=receive,date=fdate,remarks=remarks)
        moveobj.save()

    elif 'reject' in request.POST:
        fileobj.actionby_receiver="reject"
        fileobj.save()
        reqobj.tag=1
        reqobj.save()

    elif 'revert' in request.POST:
        fileobj.actionby_receiver="revert"
        fileobj.save()

        #   file=Requisitions.objects.get(pk=id)
        receive=HoldsDesignation.objects.get(designation__id=i-1)
        moveobj=Filemovement(rid=reqobj,sentby=sentby,receivedby=receive,date=fdate,remarks=remarks)
        moveobj.save()

    elif 'approve' in request.POST:
        fileobj.actionby_receiver="accept"
        fileobj.save()
        print(">>>>>>>>>>>>>")
        reqobj.tag=1
        reqobj.save()

    return HttpResponseRedirect("/office/officeOfDeanPnD/")


@login_required
def frequest(request):
    if request.method=='POST':
        form=Requisitionform(request.POST)
        print("hi")
    else:
        form=Requisitionform()

    return render(request,"officeModule/officeOfDeanPnD/viewRequisitions_content2.html",{'form':form})





def eisModulenew(request):
    project=Project_Registration.objects.all()
    project1=Project_Extension.objects.all()
    project2=Project_Closure.objects.all()
    project3=Project_Reallocation.objects.all()

    design = HoldsDesignation.objects.filter(working=request.user)
    print(design)
    desig=[]
    for i in design:
        desig.append(str(i.designation))

    context = {'project':project, 'project1':project1, 'project2':project2, 'project3':project3, 'desig':desig}

    return render(request, "eisModulenew/profile.html", context)



def officeOfPurchaseOfficr(request):
    return render(request, "officeModule/officeOfPurchaseOfficer/officeOfPurchaseOfficer.html", {})

def admin_reject(request):
    if request.method == "POST":
        marked = request.POST.getlist("selected")

        return HttpResponse("Done!")


def officeOfRegistrar(request):
    view = registrar_create_doc.objects.all()
    view2 = registrar_director_section.objects.all()
    view3 = registrar_establishment_section.objects.all()
    view4 = apply_for_purchase.objects.all()
    view5 = quotations.objects.all()
    general= registrar_general_section.objects.all()
    current_date = datetime.datetime.now()

    context = {"view":view,"view2":view2,"view3":view3,"view4":view4,"view5":view5, "current_date":current_date,"general":general}

    return render(request, "officeModule/officeOfRegistrar/officeOfRegistrar.html", context)


def upload(request):
    print("asdasdasdasd")
    docname = request.POST.get("docname")
    purpose = request.POST.get("purpose")
    description = request.POST.get("description")
    file = request.FILES['upload']
    print(file)
    request = registrar_create_doc(file_name=docname, purpose=purpose, Description=description, file=file)
    request.save()
    print(request)
    return HttpResponseRedirect("/office/officeOfRegistrar/")


@login_required(login_url='/accounts/login')
def officeOfHOD(request):
    pro = Teaching_credits1.objects.filter(tag=0)
    pro1 = Assigned_Teaching_credits.objects.all()
    context = {'pro':pro,'pro1':pro1}
    return render(request, "officeModule/officeOfHOD/officeOfHOD.html", context)


@login_required
def project_register(request):
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    project_title = request.POST.get('project_title')
    sponsored_agency=request.POST.get('sponsored_agency')
    CO_PI = request.POST.get('copi_name')
   # start_date = datetime.strptime(request.POST.get('start_date'), "%Y-%m-%d")
    start_date = request.POST.get('start_date')
    duration = request.POST.get('duration')
    #duration = datetime.timedelta('duration')
    agreement=request.POST.get('agreement')
    amount_sanctioned = request.POST.get('amount_sanctioned')
    project_type = request.POST.get('project_type')
    remarks=request.POST.get('remarks')
    #fund_recieved_date=datetime.strptime(request.POST.get('fund_recieved_date'), "%Y-%m-%d")
    project_operated = request.POST.get('project_operated')

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/after_purchase.html
{% block tab5 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab5content1">
            After Purchase Form
        </a>
    </div>

    <div class="ui active tab" data-tab="tab5content1">
        <div class="ui vertical segment">
            {% block tab5content1 %}
                {% include 'officeModule/officeOfPurchaseOfficer/after_purchase_content.html' %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/after_purchase_content.html
<div class="ui vertical segment">
        <form class= "ui form" method = "POST" id = "after_purchase" action="{% url 'office:after_purchase' %}">
            {% comment %}The add a new skill Accordian starts here!{% endcomment %}
            <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
                    {% csrf_token %}
                <div class="field">
                        <label>File number</label>
                        <input placeholder="id" class="ui large input" name= "file_no" id="file_no" >
                </div>
                
                <div class="field">
                    <label>Bill Amount</label>
                    <input placeholder="Bill amount" class="ui large input" name= "amount" id="amount" >
                </div>
                <br>
                <div class="field">
                    <label>Invoice</label>
                    <input placeholder="Invoice" type="file" name="invoice" id="invoice">
                </div>
    
                <div class="field">
                    <button class="ui primary button right floated" type="submit"name="submit" id="submit">
                        Submit
                    </button>
                </div>
            </div>
        </form>
        <br>
        <br>
    </div>
    <br>
    <div class="extra content"></div>
    

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/alerts.html
{% load static %}

{% block alerts %}
    <div class="ui centered cards" style="padding: 2px">

        {% comment %}A single card starts here!{% endcomment %}
        <div class="ui card">
            <div class="content">
                <img class="right floated circular ui image" src="{% static 'globals/img/zlatan.jpg' %}" style="width: 50px; height: auto;">
                <div class="header">
                    Mr. Rijwan Ahmed
                </div>
                <div class="meta">
                    Purchase Officer
                </div>

                <div class="ui divider"></div>

                <div class="description">
                    Registrar has approved the purchse for <br>
                    File No. 10
                </div>
            </div>
            <div class="extra content">
                <a class="ui inverted text right floated">View File</a>
            </div>
            {% comment %}
             <div class="extra content">
                <div class="ui two buttons">
                    <div class="ui basic green button">Approve</div>
                    <div class="ui basic red button">Decline</div>
                </div>
            </div>
        {% endcomment %}
        </div>
        {% comment %}A single card starts here!{% endcomment %}

        </div>
{% endblock %}

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/indentForm.html
{% block tab4 %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="tab4content1">
            Indent Form
        </a>
    </div>

    <div class="ui active tab" data-tab="tab4content1">
        <div class="ui vertical segment">
            {% block tab4content1 %}
                {% include 'officeModule/officeOfPurchaseOfficer/indentForm_content1.html' %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/manageStore_content1.html
{% comment %}The add a new skill Accordian starts here!{% endcomment %}
<form method='POST' class="ui form" style="padding: 8px; padding-left: 56px; padding-right: 12px;">
    {% csrf_token %}
    <div class="two fields">
        <div class="twelve wide field">
            <label>Item Name</label>
            <input placeholder="Search" class="ui search large input" name="item_name">
        </div>

        <div class="four wide field">
            <label><br></label>
            <button class="ui primary button" type="submit" name="item_search">
                Search
                <i class="ui right floated search icon"></i>
            </button>
        </div>
    </div>

<div class="ui divider"></div>

<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>

        <th class="two wide column">
            Sr.#
        </th>

        <th>
            Item Name
        </th>
        <th>
            Item type
        </th>

        <th class="three wide column">
            Quantity
        </th>
    </tr>
    </thead>

    <tbody>
            {% for i in q %}
            <tr>
            
            <td>
                            {{ i.id }}
            </td>
            
            <td>
                        {{ i.item_name}}
            </td>
            
            <td>
                        {% if i.item_type == 0 %}
                            Consumable
                        {% endif %}
                        {% if i.item_type == 1 %}
                            Non-consumable
                        {% endif %}
            
            </td>
                    
            <td>
                            {{ i.quantity}}
            </td>

            <td>
                    <div class="collapsing">
                    <a href="{% url 'office:delete_item' i.pk %}" class="ui red right floated button">Delete</a> 
                    </div>
            </td>
            <td>
                <div class="collapsing">
                <a href="{% url 'office:edit_item' i.pk %}" class="ui blue right floated button">Edit</a> 
                </div>
        </td>
            
            </tr>
            {% endfor %}
            
                </tbody>

    
        {% if match %}
    <tbody>
        {% for i in match %}
    <tr>
        <td>
              {{ i.id }}  
            </td>

        <td>
            {{ i.item_name}}
        </td>

        <td>
            {% if i.item_type == 0 %}
                Consumable
            {% endif %}
            {% if i.item_type == 1 %}
                Non-consumable
            {% endif %}

        </td>
        
        <td>
                {{ i.quantity}}
        </td>

        <td>
            <div class="collapsing">
            <a href="{% url 'office:delete_item' i.pk %}" class="ui red right floated button">Delete</a> 
            </div>
        </td>

    </tr>
{% endfor %}
</tbody>
{% endif %}



</table>


<br>

<!--<div class="ui right floated button">
    Edit Selected
</div>
<div>
    <button class="ui red right floated button">Delete Selected</button>
</div>
</form>
<br>
<br>-->

<div class="ui divider"></div>

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/manageStore_content2.html
<form method='POST'>
    {% csrf_token %}
    {% comment %}The add a new skill Accordian starts here!{% endcomment %}
    <div class="ui form" style="padding: 8px; padding-left: 56px; padding-right: 12px;">
        <div class="ui eight wide field">
            <label>
                Item Name
            </label>
            <input class="ui large input" placeholder="Item Name" name="item_name" type="text">
        </div>
        <div class="field">
            <label>Type of Item</label>
            <br>

                <div class="field">
                    <div class="ui large radio checkbox">
                        <input name="item_type" type="radio" value="0">
                        <label> Consumable </label>
                    </div>
                </div>

                <div class="field">
                    <div class="ui large radio checkbox">
                        <input name="item_type" type="radio" value="1">
                        <label> Non-consumable </label>
                    </div>
                </div>
        </div>

        <div class="ui eight wide field">
            <label>
                Quantity
            </label>
            <input class="ui large input" placeholder="Quantity" name="qunatity" type="number">
        </div>

        <div class="ui eight wide field">
            <label>
                <br>
            </label>
            <button class="ui right floated primary button" type="submit" name="store">Submit</button>
        </div>

    </div>
</form>

<br>
<br>

<div class="ui divider"></div>

FusionIIIT/templates/officeModule/officeOfPurchaseOfficer/vendors_content1.html
<form method='POST'>
    {% csrf_token %}
    {% comment %}The add a new skill Accordian starts here!{% endcomment %}
    <div class="ui form" style="padding: 8px; padding-left: 56px; padding-right: 12px;">
        <div class="two fields">
            <div class="twelve wide field">
                <label>Item</label>
                <input type="text" placeholder="Search" class="ui search large input" name="item">
            </div>
            

            <div class="four wide field">
                <label><br></label>
                <button class="ui primary submit button" type="submit" name="vendor_search">
                    Search
                    <i class="ui right floated search icon"></i>
                </button>
            </div>
        </div>
    </div>
</form>

<div class="ui divider"></div>

     <table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>

        <th class="two wide column">
            Sr.#
        </th>

        <th>
            Vendor Name
        </th>

        <th>
            Address
        </th>

        <th class="three wide column">
            Items
        </th>
    </tr>
    </thead>
    <tbody>
    {% if matchv %}
    {% for j in matchv %}
    <tr>
        <td>
            {{ j.id }}
        </td>

        <td>
           {{ j.vendor_name }}
        </td>
            
        <td>
                {{ j.vendor_address }}
        </td>

        <td>
                {{ j.vendor_item }}
        </td>
        <td>
                <div class="collapsing">
                        <a href="{% url 'office:delete_vendor' j.pk %}" class="ui red right floated button">Delete</a> 
                </div>
        </td>
        
       
    </tr>
    {% endfor %}
    {% endif %}

    {% for j in p %}
    <tr>
        <td>
            {{ j.id }}
        </td>

        <td>
           {{ j.vendor_name }}
        </td>
            
        <td>
                {{ j.vendor_address }}
        </td>

        <td>
                {{ j.vendor_item }}
        </td>

        <td>
                <div class="collapsing">
                        <a href="{% url 'office:delete_vendor' j.pk %}" class="ui red right floated button">Delete</a> 
                </div>
        </td>

        <td>
            <div class="collapsing">
                <a href="{% url 'office:edit_vendor' j.pk %}" class="ui blue right floated button">Edit</a> 
            </div>
    </td>
               
    </tr>
    {% endfor %}
   
    </tbody>


</table>


<br>
<!--
<div class="ui right floated button">Edit Selected</div>
<div class="ui red right floated button">Delete Selected</div>
<br>
<br>
-->

<div class="ui divider"></div>