FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^eis/', include('applications.eis.urls', namespace='eis')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls', namespace='placement')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    url(r'^aims/', include('applications.academic_information.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

FusionIIIT/applications/eis/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    # url used to add data
    url(r'uploadcsv/$', views.upload_file),
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^rspc_profile/$', views.rspc_profile, name='rspc_profile'),

    #delete
    url(r'^achv/(?P<pk>[0-9]+)/$', views.achievementDelete, name='achievement_delete'),
    url(r'^emp_confrence_organisedDelete/(?P<pk>[0-9]+)/$', views.emp_confrence_organisedDelete, name='emp_confrence_organisedDelete'),
    url(r'^emp_consultancy_projectsDelete/(?P<pk>[0-9]+)/$', views.emp_consultancy_projectsDelete, name='emp_consultancy_projectsDelete'),
    url(r'^emp_event_organizedDelete/(?P<pk>[0-9]+)/$', views.emp_event_organizedDelete, name='emp_event_organizedDelete'),
    url(r'^emp_expert_lecturesDelete/(?P<pk>[0-9]+)/$', views.emp_expert_lecturesDelete, name='emp_expert_lecturesDelete'),
    url(r'^emp_keynote_addressDelete/(?P<pk>[0-9]+)/$', views.emp_keynote_addressDelete, name='emp_keynote_addressDelete'),
    url(r'^emp_mtechphd_thesisDelete/(?P<pk>[0-9]+)/$', views.emp_mtechphd_thesisDelete, name='emp_mtechphd_thesisDelete'),
    url(r'^emp_patentsDelete/(?P<pk>[0-9]+)/$', views.emp_patentsDelete, name='emp_patentsDelete'),
    url(r'^emp_published_booksDelete/(?P<pk>[0-9]+)/$', views.emp_published_booksDelete, name='emp_published_booksDelete'),
    url(r'^emp_research_papersDelete/(?P<pk>[0-9]+)/$', views.emp_research_papersDelete, name='emp_research_papersDelete'),
    url(r'^emp_research_projectsDelete/(?P<pk>[0-9]+)/$', views.emp_research_projectsDelete, name='emp_research_projectsDelete'),
    url(r'^emp_session_chairDelete/(?P<pk>[0-9]+)/$', views.emp_session_chairDelete, name='emp_session_chairDelete'),
    url(r'^emp_techtransferDelete/(?P<pk>[0-9]+)/$', views.emp_techtransferDelete, name='emp_techtransferDelete'),
    url(r'^emp_visitsDelete/(?P<pk>[0-9]+)/$', views.emp_visitsDelete, name='emp_visitsDelete'),

    # edit personal information
    url(r'^persinfo/$', views.persinfo, name='persinfo'),

    # insert
    url(r'^pg/$', views.pg_insert, name='pg_insert'),
    url(r'^phd/$', views.phd_insert, name='phd_insert'),
    url(r'^fvisit/$', views.fvisit_insert, name='fvisit_insert'),
    url(r'^ivisit/$', views.ivisit_insert, name='ivisit_insert'),
    url(r'^journal/$', views.journal_insert, name='journal_insert'),
    url(r'^confrence/$', views.confrence_insert, name='confrence_insert'),
    url(r'^book/$', views.book_insert, name='book_insert'),
    url(r'^consym/$', views.consym_insert, name='consym_insert'),
    url(r'^event/$', views.event_insert, name='event_insert'),
    url(r'^award/$', views.award_insert, name='award_insert'),
    url(r'^talk/$', views.talk_insert, name='talk_insert'),
    url(r'^chaired/$', views.chaired_insert, name='chaired_insert'),
    url(r'^keynote/$', views.keynote_insert, name='keynote_insert'),
    url(r'^project/$', views.project_insert, name='project_insert'),
    url(r'^consult_insert/$', views.consult_insert, name='consult_insert'),
    url(r'^patent_insert/$', views.patent_insert, name='patent_insert'),
    url(r'^transfer_insert/$', views.transfer_insert, name='transfer_insert'),

    # generate report
    url(r'^report/$', views.generate_report, name='generate_report'),
    url(r'^rspc_report/$', views.rspc_generate_report, name='rspc_generate_report'),

]

FusionIIIT/applications/feeds/urls.py
from django.conf.urls import url

from . import views

app_name = 'feeds'

urlpatterns=[
	url(r'^$', views.feeds, name= 'feeds'),
	url(r'^request/$', views.Request, name= 'request'),
	url(r'^comment_text/$', views.Comment_Text, name='comment_text'),
	url(r'^reply_text/$', views.Reply_Text, name='reply_text'),
	url(r'^like_comment/$', views.LikeComment, name='like_comment'),
	url(r'^(?P<id>[0-9]+)/delete_post/$', views.delete_post, name='delete_post'),
	url(r'^(?P<id>[0-9]+)/update_post/$', views.update_post, name='update_post'),
	url(r'^(?P<string>[-\w]+)/$', views.TagsBasedView, name= 'tag_based_view'),
	url(r'^remove_tag/$', views.RemoveTag, name= 'remove_tag'),
	url(r'^question_id_/(?P<id>[0-9]+)/$', views.ParticularQuestion, name= 'single_question'),
]

FusionIIIT/applications/office_module/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'office'

urlpatterns = [

    url(r'^officeOfDeanPnD/submit$',views.submitRequest,name='pWorkRequest'),
    url(r'^officeOfDeanPnD/action$',views.action,name='action'),
    url(r'^officeOfPurchaseOfficer/',views.officeOfPurchaseOfficer, name ='officeOfPurchaseOfficer'),
    url(r'^apply_purchase/', views.apply_purchase, name='apply_purchase'),
    url(r'^after_purchase/', views.after_purchase, name='after_purchase'),
    url(r'^officeOfRegistrar/$', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^officeOfDeanRSPC/$', views.officeOfDeanRSPC, name='officeOfDeanRSPC'),

    url(r'^officeOfDeanRSPC/submit/$',views.project_register,name='p_register'),
    url(r'^officeOfDeanRSPC/extention/$',views.project_extension,name='p_extension'),
    url(r'^officeOfDeanRSPC/close/$',views.project_closure,name='p_closure'),
    url(r'^officeOfDeanRSPC/reallocate/$',views.project_reallocation,name='p_reallocation'),
    url(r'^officeOfDeanRSPC/action/$',views.project_registration_permission,name='registration'),
    url(r'^officeOfDeanRSPC/extension/$',views.project_extension_permission,name='extension'),
    url(r'^officeOfDeanRSPC/closure/$',views.project_closure_permission,name='closure'),
    url(r'^officeOfDeanRSPC/reallocation/$',views.project_reallocation_permission,name='reallocation'),
    url(r'^officeOfDeanRSPC/forwarded/$',views.hod_action,name='hod_action'),
    url(r'^officeOfDeanRSPC/forwarded1/$',views.hod_closure,name='hod_closure'),
    url(r'^officeOfDeanRSPC/forwarded2/$',views.hod_extension,name='hod_extension'),
    url(r'^officeOfDeanRSPC/forwarded3/$',views.hod_allocation,name='hod_allocation'),
    url(r'^officeOfDeanRSPC/(?P<pr_id>[0-9]+)/$',views.pdf,name='pdf'),

    url(r'^eisModulenew/profile', views.eisModulenew, name='eisModulenew'),

    url(r'^officeOfDeanPnD/$', views.officeOfDeanPnD, name='officeOfDeanPnD'),
    url(r'^officeOfHOD/$', views.officeOfHOD, name='officeOfHOD'),
    url(r'^officeOfHOD/submit/$',views.teaching_form,name='teaching_form'),
    url(r'^officeOfHOD/work/$',views.hod_work,name='hod_work'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^deleteitem/(?P<id>[0-9]+)',views.delete_item, name='delete_item'),
    url(r'^deletevendor/(?P<id>[0-9]+)',views.delete_vendor, name='delete_vendor'),
    url(r'^editvendor/(?P<id>[0-9]+)',views.edit_vendor, name='edit_vendor'),
    url(r'^editvendor/office/officeOfPurchaseOfficer/edit/',views.edit,name='edit'),
    url(r'^edititem/(?P<id>[0-9]+)',views.edit_item, name='edit_item'),
    url(r'^edititem/office/officeOfPurchaseOfficer/edit1/',views.edit1,name='edit'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^directorOffice/$', views.directorOffice, name='directorOffice'),
    url(r'^directorOffice/appoint', views.appoint, name='appoint'),
    url(r'^directorOffice/meeting', views.meeting, name='meeting'),
    url(r'^officeOfRegistrar/upload/$', views.upload, name='upload'),
    url(r'^officeOfRegistrar/generalAdminForm/reject/$', csrf_exempt(views.admin_reject), name='admin_reject'),
    url(r'^officeOfDeanStudents/$', views.officeOfDeanStudents, name='officeOfDeanStudents'),
    url(r'^officeOfPurchaseOfficer/', views.officeOfPurchaseOfficr, name='officeOfPurchaseOfficer'),
    url(r'^officeOfRegistrar/', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^officeOfDeanStudents/holding_meeting', views.holdingMeeting, name='holdingMeetings'),
    url(r'^officeOfDeanStudents/meeting_Minutes', views.meetingMinutes, name='meetingMinutes'),
    url(r'^officeOfDeanStudents/hostelRoomAllotment', views.hostelRoomAllotment),
    url(r'^officeOfDeanStudents/budget_approval', views.budgetApproval),
    url(r'^officeOfDeanStudents/budget_rejection', views.budgetRejection),
    url(r'^officeOfDeanStudents/club_approval', views.clubApproval),
    url(r'^officeOfDeanStudents/club_rejection', views.clubRejection),
    url(r'^officeOfDeanStudents/budgetAllot', views.budgetAllot),
    url(r'^officeOfDeanStudents/budgetAllotEdit', views.budgetAllotEdit),
    url(r'^officeOfDeanAcademics/$', views.officeOfDeanAcademics, name='officeOfDeanAcademics'),

    url(r'^officeOfDeanAcademics/assistantship', views.assistantship, name='assistantship'),
    url(r'^officeOfDeanAcademics/formsubmit', views.formsubmit, name='formsubmit'),
    url(r'^officeOfDeanAcademics/init_assistantship', views.init_assistantship, name='init_assistantship'),
    url(r'^officeOfDeanAcademics/scholarshipform', views.scholarshipform),
    url(r'^officeOfDeanAcademics/applications', views.applications, name='applications'),
    url(r'^officeOfDeanAcademics/courses', views.courses, name='courses'),
    url(r'^officeOfDeanAcademics/scholarship', views.scholarship, name='scholarship'),
    url(r'^officeOfDeanAcademics/semresults', views.semresults, name='semresults'),
    url(r'^officeOfDeanAcademics/thesis', views.thesis, name='thesis'),
]

FusionIIIT/applications/urls.py
from django.conf.urls import url

from . import views

app_name = 'filetracking'

urlpatterns = [

    url(r'^$', views.filetracking, name='filetracking'),
    url(r'^drafts/$', views.drafts, name='drafts'),
    url(r'^outward/$', views.outward, name='outward'),
    url(r'^inward/$', views.inward, name='inward'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^finish/(?P<id>\d+)/$', views.finish, name='finish'),
    url(r'^forward/(?P<id>\d+)/$', views.forward, name='forward'),
]

FusionIIIT/applications/academic_procedures/models.py
import datetime

from django.db import models

from applications.academic_information.models import Course, Student
from applications.globals.models import DepartmentInfo, ExtraInfo, Faculty


class Constants:
    SEM_CHOICES = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
    )

    MTechSpecialization = (
        ('Power and Control', 'Power and Control'),
        ('Microwave and Communication Engineering', 'Microwave and Communication Engineering'),
        ('Micro-nano Electronics', 'Micro-nano Electronics'),
        ('CAD/CAM', 'CAD/CAM'),
        ('Design', 'Design'),
        ('Manufacturing', 'Manufacturing'),
        ('CSE', 'CSE'),
        ('Mechatronics', 'Mechatronics'),
        ('MDes', 'MDes'),
        ('all', 'all')
    )


class Register(models.Model):
    r_id = models.IntegerField(primary_key=True)
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    year = models.IntegerField(default=datetime.datetime.now().year)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    semester = models.IntegerField()

    class Meta:
        db_table = 'Register'

    def __str__(self):
        return str(self.course_id)


class Thesis(models.Model):
    reg_id = models.ForeignKey(ExtraInfo, on_delete=models.CASCADE)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    supervisor_id = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    topic = models.CharField(max_length=1000)

    class Meta:
        db_table = 'Thesis'

    def __str__(self):
        return str(self.topic) + " " + str(self.student_id)


class FinalRegistrations(models.Model):
    reg_id = models.ForeignKey(ExtraInfo, on_delete=models.CASCADE)
    semester = models.IntegerField()
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    registration = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class BranchChange(models.Model):
    c_id = models.AutoField(primary_key=True)
    branches = models.ForeignKey(DepartmentInfo, on_delete=models.CASCADE)
    user = models.ForeignKey(Student, on_delete=models.CASCADE)
    applied_date = models.DateField(default=datetime.datetime.now)

    def __str__(self):
        return str(self.user) + " " + str(self.branches)


class CoursesMtech(models.Model):
    c_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    specialization = models.CharField(max_length=30, choices=Constants.MTechSpecialization)

    def __str__(self):
        return str(self.c_id)


class MinimumCredits(models.Model):
    semester = models.IntegerField()
    credits = models.IntegerField()

    def __str__(self):
        return "Semester: " + str(self.semester)+" Credits:" + str(self.credits)

FusionIIIT/applications/academic_information/forms.py
from django import forms

from .models import Exam_timetable, Meeting, Timetable


class MinuteForm(forms.ModelForm):
    """
    the form to add a new senate meeting minutes to the database.
    It consist of date and file upload

    @attrubutes:
        model - the model used is the Meeting class
        fields - the fields shown in the form for the user to fill up is date and file upload
        widgets - defining the id, required and placeholder of the filed in the form

    """
    class Meta:
        model = Meeting
        fields = ('date', 'minutes_file', )


class AcademicTimetableForm(forms.ModelForm):
    """
    the form to add a new academic timetable to the database.
    It consist of year, programme and the timetable file upload

    @attrubutes:
        model - the model used is the Timetable class
        fields - the fields shown in the form for the user to fill up is year, programme and timetable file upload
        widgets - defining the id, required and placeholder of the filed in the form

    """
    class Meta:
        model = Timetable
        fields = ('year', 'programme', 'time_table',)


class ExamTimetableForm(forms.ModelForm):
    """
    the form to add a new eaxam timetable to the database.
    It consist of year, programme and exam timetable file

    @attrubutes:
        model - the model used is the Exan_timetable class
        fileds - the fields shown in the form for the user to fill up is year, programme and exam timtable file to upload
        widgets - defining the id, required and placeholder of the filed in the form

    """
    class Meta:
        model = Exam_timetable
        fields = ('year', 'programme', 'exam_time_table',)

FusionIIIT/applications/academic_procedures/forms.py
from django import forms

from applications.academic_information.models import Course


class AddDropCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AddDropCourseForm, self).__init__(*args, **kwargs)

    courses = forms.ModelChoiceField(queryset=Course.objects.all())

    class Meta:
        model = Course
        fields = ('course_id', 'course_name', 'sem', 'credits', 'courses')

FusionIIIT/templates/officeModule/officeOfDeanRSPC/Hod_Applications_content.html
{% load static %}

<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column">
        </th>

        <th class="one wide column">
            Faculty Name
        </th>

        <th class="one wide column">
            Project Title
        </th>

        <th class="four wide column">
            project type
        </th>

        <th class="four wide column">
            Status
        </th>

        <th class="four wide column">
            Date
        </th>
         <th class="four wide column">
            view Details
        </th>
    </tr>
    </thead>

    <tbody>
    <h2> Project Registration Form </h2>
    <form action="{% url 'office:hod_action' %}" method="POST">
        {% csrf_token %}
         {% for pr in project %}
        
    <tr>

        <td class="collapsing">
            <div class="ui fitted checkbox">
                <input type="checkbox" value={{pr.id}} name="id"> <label></label>
            </div>
        </td>

        <td>
             {{pr.PI_id}}
        </td>

        <td>
             {{pr.project_title}}
        </td>

        <td>
             {{pr.project_type}}
        </td>

        <td>
            <i class="large red crossmark icon">{{pr.HOD_response}}</i>
        </td>

        <td>

            {{pr.start_date}}
            
        </td>
        <td>
           <a href="/office/officeOfDeanRSPC/{{pr.id}}/" target="_blank">Details</a>
        </td>

   
 </tr>
 {% endfor%}
    </tbody>
</table>
<br>
<button class="ui primary right floated button" type="submit" name="forward" value="forward">Forward Selected</button>

</form>
<br><br>

 <h2> Project closure Form </h2><br>
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column">
        </th>

        <th class="one wide column">
            Faculty Name
        </th>

        <th class="one wide column">
            Project Title
        </th>

        <th class="four wide column">
            project type
        </th>

        <th class="four wide column">
            Status
        </th>

        <th class="four wide column">
            Date
        </th>
         <th class="four wide column">
            view Details
        </th>
    </tr>
    </thead>

    <tbody>
   
    <form action="{% url 'office:hod_closure' %}" method="POST">
        {% csrf_token %}
       {% for pr in project2 %}
        <tr>
        <td class="collapsing">
            <div class="ui fitted checkbox">
                <input type="checkbox" value={{pr.id}} name="id"> <label></label>
            </div>
        </td>

         <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.PI_id}}
                {%endif%}
            {%endfor%}
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_title}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_type}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            <i class="large red crossmark icon">{{pr.HOD_response}}</i>
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.start_date}}
                {%endif%}
            {%endfor%}
            
            
        </td>
        <td>
           <a href="/office/officeOfDeanRSPC/{{pr.id}}/" target="_blank">Details</a>
        </td>

    </tr>

 {% endfor%}
    </tbody>
</table>
<br>
<button class="ui primary right floated button" type="submit" name="forward" value="forward">Forward Selected</button>

</form>


<br><br>

<h2> Project Extension Form </h2><br>
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column">
        </th>

        <th class="one wide column">
            Faculty Name
        </th>

        <th class="one wide column">
            Project Title
        </th>

        <th class="four wide column">
            project type
        </th>

        <th class="four wide column">
            Status
        </th>

        <th class="four wide column">
            Date
        </th>
         <th class="four wide column">
            view Details
        </th>
    </tr>
    </thead>

    <tbody>
    <form action="{% url 'office:hod_extension' %}" method="POST">
        {% csrf_token %}
       {% for pr in project1 %}
        <tr>
        <td class="collapsing">
            <div class="ui fitted checkbox">
                <input type="checkbox" value={{pr.id}} name="id"> <label></label>
            </div>
        </td>

         <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.PI_id}}
                {%endif%}
            {%endfor%}
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_title}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_type}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            <i class="large red crossmark icon">{{pr.HOD_response}}</i>
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.start_date}}
                {%endif%}
            {%endfor%}
            
            
        </td>
        <td>
           <a href="/office/officeOfDeanRSPC/{{pr.id}}/" target="_blank">Details</a>
        </td>

    </tr>

 {% endfor%}
    </tbody>
</table>
<br>
<button class="ui primary right floated button" type="submit" name="forward" value="forward">Forward Selected</button>

</form>


<br><br>

<br>

<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column">
        </th>

        <th class="one wide column">
            Faculty Name
        </th>

        <th class="one wide column">
            Project Title
        </th>

        <th class="four wide column">
            project type
        </th>

        <th class="four wide column">
            Status
        </th>

        <th class="four wide column">
            Date
        </th>
         <th class="four wide column">
            view Details
        </th>
    </tr>
    </thead>

    <tbody>
        <h2> Project Reallocation Form </h2>
    <form action="{% url 'office:hod_allocation' %}" method="POST">
        {% csrf_token %}
     {% for pr in project3 %}
        <tr>
        <td class="collapsing">
            <div class="ui fitted checkbox">
                <input type="checkbox" value={{pr.id}} name="id"> <label></label>
            </div>
        </td>

         <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.PI_id}}
                {%endif%}
            {%endfor%}
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_title}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.project_type}}
                {%endif%}
            {%endfor%}
             
        </td>

        <td>
            <i class="large red crossmark icon">{{pr.HOD_response}}</i>
        </td>

        <td>
            {% for pr1 in project %}
                {%if pr1 == pr.project_id %}
                    {{pr1.start_date}}
                {%endif%}
            {%endfor%}
            
            
        </td>
        <td>
           <a href="/office/officeOfDeanRSPC/{{pr.id}}/" target="_blank">Details</a>
        </td>

    </tr>

 {% endfor%}
    </tbody>
</table>
<br>
<button class="ui primary right floated button" type="submit" name="forward" value="forward">Forward Selected</button>

</form>

<br>
<br>
<div class="ui divider"></div>

<div class="extra content">
    <div class="" style="text-align: center;">
        <i class="large green checkmark icon"></i> : Approved &ensp;&ensp;&ensp;&ensp;&ensp;
        <i class="large orange warning icon"></i> : Pending &ensp;&ensp;&ensp;&ensp;&ensp;
        <i class="large red x icon"></i> : Declined
    </div>
</div>

FusionIIIT/templates/officeModule/officeOfDeanRSPC/alerts.html
{% load static %}

{% block alerts %}
    <div class="ui centered cards" style="padding: 2px">

        {% comment %}A single card starts here!{% endcomment %}
        <div class="ui card">
            <div class="content">
                <img class="right floated circular ui image" src="{% static 'globals/img/zlatan.jpg' %}" style="width: 50px; height: auto;">
                <div class="header">
                    Dr. Vinod Kumar Jain
                </div>
                <div class="meta">
                    Associate Professor
                </div>

                <div class="ui divider"></div>

                <div class="description">
                    Notification and/or alerts for this module goes here!
                </div>
            </div>
            <div class="extra content">
                <div class="ui two buttons">
                    <div class="ui basic green button">Approve</div>
                    <div class="ui basic red button">Decline</div>
                </div>
            </div>
        </div>
        {% comment %}A single card starts here!{% endcomment %}

    </div>
{% endblock %}