FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^feeds/', include('applications.feeds.urls')),
    url(r'^eis/', include('applications.eis.urls', namespace='eis')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls', namespace='placement')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    url(r'^aims/', include('applications.academic_information.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

FusionIIIT/applications/central_mess/urls.py
from django.conf.urls import url

from . import views

app_name = 'mess'

urlpatterns = [

    url(r'^$', views.mess, name='mess'),
    url(r'^placeorder/', views.placeorder, name='placeorder'),
    url(r'^submit/', views.submit, name='submit'),
    url(r'^vacasubmit/', views.vacasubmit, name='vacasubmit'),
    url(r'^menusubmit/', views.menusubmit, name='menusubmit'),
    url(r'^regsubmit/', views.regsubmit, name='regsubmit'),
    url(r'^regadd/', views.regadd, name='regadd'),
    url(r'^(?P<ap_id>[0-9]+)/response/', views.response, name='response'),
    url(r'^(?P<ap_id>[0-9]+)/processvacafood/', views.processvacafood, name='processvacafood'),
    url(r'^leave', views.leaverequest, name='leaverequest'),
    url(r'^invitation', views.invitation, name='invitation'),
    url(r'^minutes', views.minutes, name='minutes'),
    url(r'^placerequest', views.placerequest, name='placerequest'),
    url(r'^(?P<ap_id>[0-9]+)/responserebate/', views.responserebate, name='responserebate'),
    url(r'^(?P<ap_id>[0-9]+)/responsespl/', views.responsespl, name='responsespl'),
    url(r'^updatecost', views.updatecost, name='updatecost'),

]

FusionIIIT/templates/messModule/changemenu.html
{% load static %}
{% block changemenu %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="changemenu">
            Request For Menu Change
        </a>
    </div>
    <div class="ui active tab" data-tab="changemenu">
        <div class="ui vertical segment">

            {% comment %}Form Tag starts here!{% endcomment %}
            {% comment %}The add a new skill Accordian starts here!{% endcomment %}
            <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">

                <div class="ui header">
                    Menu Card:
                </div>
                <br>

                <div class="ui stackable grid doubling">
                    <div class="ui row">
                        <div class="four wide column">
                            <div class="ui secondary vertical pointing small menu">
                                <a class="active item" data-tab="changemenu">
                                    Change Menu
                                </a>
                            </div>
                        </div>
                        <div class="ui twelve wide column">
                            <div class="ui active tab" data-tab="changemenu">
                                <form class="ui form" method="post" action="{% url 'mess:menusubmit'%}">
                                    {% csrf_token %}
                                    <div class="ui row">
                                        <div class="three fields">
                                            <div class="field">
                                                <label>
                                                    Dish
                                                </label>

                                                <select class="ui search fluid dropdown" name="dish" id="dish">
                                                    {% for item in menu %}
                                                    <option value="{{item.dish}}">{{item.dish}}-{{item.meal_time}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>

                                            <div class="field">
                                                <label>
                                                    Change To
                                                </label>

                                                <div class="ui input">
                                                    <input placeholder="Food" name="newdish" required>
                                                </div>
                                            </div>

                                            <div class="field">
                                                <label>
                                                    Reason
                                                </label>

                                                <div class="ui input">
                                                    <input placeholder="Why?" name="reason" required="true">
                                                </div>
                                            </div>

                                        </div> 
                                    </div>
                                

                                    <div class="ui row">
                                        <br>
                                        <button type="submit" class="ui primary button right floated">
                                            Place Request
                                        </button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

FusionIIIT/templates/messModule/feedback.html
{% extends 'globals/base.html'%}
{% load static %}
{% block body %}
{% block feedback %}
    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="feedback">
            Feedback
        </a>

        <a class="item" data-tab="viewfeedback">
            Status
        </a>
    </div>

    <div class="ui active tab" data-tab="feedback">
        <div class="ui vertical segment">

            {% comment %}Form Tag starts here!{% endcomment %}
            <form method="POST">
                {% csrf_token %}
                {% comment %}The add a new skill Accordian starts here!{% endcomment %}
                <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">

                    <div class="ui header">
                        The Feedback form for Mess:
                    </div>

                    <br>

                    <div class="two fields">
                        <div class="field">
                            <label>Mess:</label>
                            <input value={{messinfo.mess_option}} class="ui large input" readonly>
                        </div>

                        <div class="two fields">
                            <div class="twelve wide field">
                                <label>Type:</label>
                                <select class="ui search fluid dropdown" name="feedback_type" id="feedback_type">
                                    <option value="Cleanliness">Cleanliness</option>
                                    <option value="Food">Food</option>
                                    <option value="Maintainence">Maintainence</option>
                                    <option value="Others">Others</option>
                                </select>
                            </div>

                            <!-- <div class="field">
                                <label><br></label>
                                <button class="ui primary fluid button" type="submit">
                                    Submit
                                </button>
                            </div> -->
                        </div>
                    </div>

                    <div class="field">
                        <label>Description:</label>
                        <textarea rows="2" id="description" name="description" required="true"></textarea>
                    </div>
                    
                    <div class="field">
                        <label><br></label>
                            <button class="ui primary fluid button" onclick="return feedback()">
                            Submit
                            </button>
                    </div>

                </div>
            </form>
            {% comment %}Form Tag ends here!{% endcomment %}


            <div class="ui divider"></div>

        </div>
    </div>

    <div class="ui tab" data-tab="viewfeedback">
        {% for app in feedback %}
        <div class="ui very relaxed fluid selection list" style="padding-left: 24px; padding-top: 16px; padding-bottom: 16px; max-height: 70vh; overflow-y: auto;">
            
            <div class="item">
                <img class="ui mini circular image" src="{% static 'globals/img/zlatan.jpg' %}">
                <div class="content">
                    <a class="header">{{info.user.username}}</a>
                    <span class="meta">{{app.feedback_type}}</span>

                    <div class="description">
                        {{app.description}}
                    </div>
                </div>

                <div class="right floated content">
                    <span class="meta">{{app.fdate}}</span>
                </div>
                
            </div>

        </div>
        {% endfor %}
    <div class="ui divider"></div>
    </div>

{% endblock %}
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'globals/js/jquery.min.js' %}"></script>

 <script>
        function feedback(){
            $.ajax({
                type: 'POST',
                url: 'submit/',
                dataType: 'json',
                data: {
                    'csrfmiddlewaretoken' : '{{ csrf_token }}',
                    'feedback_type':$("#feedback_type").val(),
                    'description':$("#description").val(),
                },                
                success: function(data) {
                    if(data.status){
                        alert("Data Inserted Successfully");
                        
                        // $('#ls_table').prepend("<tr><td>"+ $("#leave_type").val()+ "</td><td>"+ 
                        //     $("#start_date").val() + "</td><td>" + $("end_date").val()+
                        //     "</td><td>"+ $("#purpose").val()+ "</td></tr>")

                        document.getElementById('feedback_type').value="";
                        document.getElementById('description').value="";
                        
                    }
                },
                error: function(data, err) {
                    alert(err.message);
                }
            });
        return false;
    }
    


</script>
{% endblock %}

FusionIIIT/templates/messModule/invitation.html
{% extends 'globals/base.html' %}
{% load static %}
{% block body %}
{% block invitation %}
<div class="ui pointing secondary menu">
    <a class="active item" data-tab="invitation">
        Meeting Invitation
    </a>
</div>
<div class="ui active tab" data-tab="invitation">
    <div class="ui vertical stripe team segment"
         style="padding-left: 3.5%;
                padding-right: 3.5%;">

        <form  method="POST" class="ui large form" action="{% url 'mess:invitation' %}">
            {% csrf_token %}

            {% comment %} The invitation form  starts here! {% endcomment %}

            {% comment %}The form row starts here!{% endcomment %}


            <div class="two fields">
                <div class="field">
                    <label>Date</label>
                    <!-- <div class="ui calendar" id="rangestart">
                        <div class="ui input left icon">
                            <i class="calendar icon"></i> -->
                            <input  name="date" type="date" placeholder="Date" required="true" id="date">
                        <!-- </div>
                    </div> -->
                </div>

                <div class="field">
                    <label>Time</label>
                    <input name="time" type="time" required="true" id="time">
                </div>

            </div>
            <div class="two fields">
                <div class="field">
                    <label>Agenda</label>
                    <input name="agenda" placeholder="Agenda" type="text" required="true" id="agenda">
                </div>
                 <div class="field">
                    <label>Place</label>
                                <select  name="venue" class="ui fluid dropdown" required="true" id="venue">
                                    <option value="Cm1">Central Mess I</option>
                                    <option value="Cm2">Central Mess II</option>
                                </select>

                </div>

            </div>
            <div class="field">
                   <label>Description:</label>
                        <textarea name="description" rows="2" required="true" id="description"></textarea>
            </div>

            <div class="field">
                                <label><br></label>
                                <button class="ui primary right floated button">
                                    Submit
                                </button>


            </div>
            <br>

        </form>
        <div class="ui divider"></div>

        <table class="ui very basic collapsing celled table sortable centered" style="margin: auto;">
                <thead>
                <tr>
                    <th>Meeting Date</th>
                    <th>Venue</th>
                    <th>Agenda</th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody id="invitation_table">
                    {% for item in meeting %}
                <tr>
                    <td>{{item.meet_date}}</td>
                    <td>{{item.venue}}</td>
                    <td>{{item.agenda}}</td>
                    <td>{{item.meeting_time}}</td>
                </tr>
                    {% endfor %}
                </tbody>
            </table>

    </div>
    </div>

<!-- <script type="text/javascript" src="{% static 'globals/js/jquery.min.js' %}"></script>

<script type="text/javascript">

    function invitation(){
            $.ajax({
                type: 'POST',
                url: 'invitation/',
                dataType: 'json',
                data: {
                    'date':$("#date").val(),
                    'agenda':$("#agenda").val(),
                    'venue':$("#venue").val(),
                    'time':$("#time").val()
                },                
                success: function(data) {
                    if(data.status == 1){
                        alert("Data Inserted Successfully");

                        $("#invitation_table").prepend("<tr><td>"+ $("#date").val() +"</td><td>"+
                            $("#venue").val() + "</td><td>"+ $("#agenda").val() +"</td><td>"+
                            $("#time").val(), +"</td></tr>")

                        document.getElementById('date').value="";
                        document.getElementById('agenda').value="";
                        document.getElementById('venue').value="";
                        document.getElementById('time').value="";
                        document.getElementById('description').value="";

                    }
                },
                error: function(data, err) {
                    alert(err.message);
                }
            });
        return false;
        }

</script>     -->

{% endblock %}
{% endblock %}

FusionIIIT/templates/messModule/minutes.html
{% extends 'globals/base.html' %}
{% load static %}
{% block body %}
{% block minutes %}
<div class="ui pointing secondary menu">
    <a class="active item" data-tab="minutes">
        Meeting Minutes
    </a>
</div>
<div class="ui active tab" data-tab="minutes">
    <div class="ui vertical stripe team segment"
         style="padding-left: 3.5%;
                padding-right: 3.5%;">

        <form class="ui form" method="POST" enctype="multipart/form-data" id="minutes" action="{% url 'mess:minutes' %}">
            {% csrf_token %}
                <div class="field">
                    <div class="three fields">
                        {{form.as_p}}
                        <div class="field">
                            <label><br></label>
                            <input type="submit" value="Save" />
                        </div>
                    </div>
                </div>            
        </form>
        <div class="ui divider"></div>

        <table class="ui very basic collapsing celled table sortable centered" style="margin: auto;">
                <thead>
                <tr>
                    <th>Meeting Date - Agenda</th>
                    <th>Minutes</th>
                </tr>
                </thead>
                <tbody>
                    {% for item in minutes %}
                <tr>
                    <td>{{item.meeting_date}}</td>
                    <td><a href="{{item.mess_minutes.url}}">{{item.mess_minutes}}</a></td>
                </tr>
                {% endfor %}
                </tbody>
        </table>

    </div>
</div>

{% endblock %}
{% endblock %}

FusionIIIT/templates/messModule/nonvegfood.html
{% extends 'globals/base.html'%}
{% load static %}
{% block body %}
{% block nonvegfood %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="active item" data-tab="nonvegfood">
            Non-Vegetarian Food
        </a>

        <a class="item" data-tab="nonvegfoodhistory">
            History
        </a>
    </div>

    <div class="ui active tab" data-tab="nonvegfood">
        <div class="ui vertical segment">

            {% comment %}Form Tag starts here!{% endcomment %}
            <form method="post" action="{% url 'mess:placeorder' %}">
                {% csrf_token %}
                {% comment %}The add a new skill Accordian starts here!{% endcomment %}
                <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">

                    <div class="ui header">
                        A la Carte:
                    </div>

                    <br>

                    <div class="ui stackable grid doubling">
                        <div class="ui row">
                            <div class="four wide column">
                                <div class="ui secondary vertical pointing small menu">
                                    <a class="active item" data-tab="breakfast">
                                        Breakfast
                                    </a>

                                    <a class="item" data-tab="lunch">
                                        Lunch
                                    </a>

                                    <a class="item" data-tab="dinner">
                                        Dinner
                                    </a>
                                </div>
                            </div>

                            <div class="ui twelve wide column">
                                <div class="ui active tab" data-tab="breakfast">
                                    <form class="ui form" method="post" action="{% url 'mess:placeorder' %}">
                                        <div class="ui row">
                                            <div class="two fields">
                                                {% for x in nonveg %}
                                                    {% if x.order_interval == 'Breakfast' %}
                                                <div class="field">
                                                    <input type="text" name="interval" value="breakfast" hidden>
                                                    <div class="ui input">
                                                        <input type="radio" name='dish' value='{{x.dish}}' id="dish">{{x.dish}} - {{x.price}}
                                                    </div>
                                                </div>
                                                    {% endif %}
                                                {% endfor %}
                                                
                                            </div>
                                        </div> 

                                        <div class="ui row">
                                            <br>
                                            <button type="submit" id="submit" class="ui primary button right floated">
                                                Place Order
                                            </button>
                                        </div>
                                    </form>
                                </div>

                                <div class="ui tab" data-tab="lunch">
                                    <form class="ui form" method="post" action="{% url 'mess:placeorder' %}">
                                        {% csrf_token %}
                                        <div class="ui row">
                                            <div class="two fields">
                                            {% for x in nonveg %}
                                                    {% if x.order_interval == 'Lunch' %}
                                                <div class="field">

                                                    <div class="ui input">
                                                        <input type="text" name="interval" value="lunch" hidden>
                                                        <input type="radio" name='dish' value='{{x.dish}}' id="">{{x.dish}} - {{x.price}}
                                                    </div>
                                                </div>
                                                    {% endif %}
                                            {% endfor %}

                                            </div>
                                        </div>

                                        <div class="ui row">
                                            <br>
                                            <button type="submit" id="submit" class="ui primary button right floated">
                                                Place Order
                                            </button>
                                        </div>
                                    </form>
                                </div>

                                <div class="ui tab" data-tab="dinner">
                                    <form class="ui form" method="post" action="{% url 'mess:placeorder' %}">
                                        {% csrf_token %}
                                        <div class="ui row">
                                            
                                            <div class="two fields">
                                                {% for x in nonveg %}
                                                    {% if x.order_interval == 'Dinner' %}
                                                <div class="field">

                                                    <div class="ui input">
                                                        <input type="text" name="interval" value="dinner" hidden>
                                                        <input type="radio" name='dish' value='{{x.dish}}' id="dish">{{x.dish}} - {{x.price}}
                                                    </div>
                                                </div>
                                                    {% endif %}
                                                {% endfor %}

                                            </div>
                                        </div>

                                        <div class="ui row">
                                            <br>
                                            <button type="submit" id="submit" class="ui primary button right floated">
                                                Place Order
                                            </button>
                                        </div>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </form>
            {% comment %}Form Tag ends here!{% endcomment %}

            <br>

            <div class="ui divider"></div>

        
        </div>
    </div>

    <div class="ui tab" data-tab="nonvegfoodhistory">
        <div class="ui vertical segment">

            {% comment %} Rupee sign is &#8377; {% endcomment %}
            <table class="ui very basic collapsing celled large sortable table"
                   style="padding-left: 2.5%;
                                                          padding-right: 2.5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
                <thead>
                    <tr>
                        <th>
                            Student
                        </th>

                        <th>
                            Date
                        </th>

                        <th>
                            Type
                        </th>

                        <th>
                            Food Item
                        </th>

                        <th>
                            Qty.
                        </th>

                        <th>
                            Amt.
                        </th>
                    </tr>
                </thead>

                <tbody>
                    {% for info in data %}
                    <tr>
                        <td>
                            <h4 class="ui image header">
                                <img src="{% static 'globals/img/zlatan.jpg' %}" class="ui mini circular image">
                                <div class="content">
                                    {{info.student_id}}
                                </div>
                            </h4>
                        </td>

                        <td>
                            {{info.order_date}}
                        </td>

                        <td>
                            {{info.order_interval}}
                        </td>

                        <td>
                            {{info.dish}}
                        </td>

                        <td>
                            1
                        </td>

                        <td>
                            &#8377; {{info.dish.price}}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>

            <br>
            <div class="ui divider"></div>
        </div>
    </div>
{% endblock %}
{% endblock %}

FusionIIIT/templates/messModule/registration.html
{% load static %}
{% block registration %}

    {% comment %}The tab menu starts here!{% endcomment %}
    <div class="ui pointing secondary menu">
        <a class="ui active item" data-tab="messchange">
            Mess Change
        </a>
    </div>
    
    <div class="ui active tab" data-tab="messchange">
        <div class="ui vertical segment">

            {% comment %}Form Tag starts here!{% endcomment %}

            {% if current_date < mess_reg.end_reg %}
            Registration ongoing till {{mess_reg.end_reg}}

            {% else %}
            <form method="post" action="{% url 'mess:regadd' %}">
                {% csrf_token %}
                <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">


                    <br>
                    <div class="two fields">
                        <div class="field">
                            <label>Choose Sem:</label>
                            <select class="ui search fluid dropdown" name="sem">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                            </select>
                        </div>
                    </div>
                    
                    <div class="field">
                        <label>Start date:</label>
                        <input type="date" name="start_date">
                    </div>

                    <div class="field">
                        <label>End date:</label>
                        <input type="date" name="end_date">
                    </div>

                    <div class="field">
                        <button class="ui primary button right floated" type="submit" name="submit">
                            Submit
                        </button>
                    </div>
                </div>
            </form>
            
            {% endif %}
            {% comment %}Form Tag ends here!{% endcomment %}

            <br>
            <br>
            <div class="ui divider"></div>

        </div>
    </div>
{% endblock %}